export const TOURNAMENT_LIST_REQUEST = "TOURNAMENT_LIST_REQUEST";
export const TOURNAMENT_LIST_SUCCESS = "TOURNAMENT_LIST_SUCCESS";
export const TOURNAMENT_LIST_FAIL = "TOURNAMENT_LIST_FAIL";

export const TOURNAMENT_DETAILS_REQUEST = "TOURNAMENT_DETAILS_REQUEST";
export const TOURNAMENT_DETAILS_SUCCESS = "TOURNAMENT_DETAILS_SUCCESS";
export const TOURNAMENT_DETAILS_FAIL = "TOURNAMENT_DETAILS_FAIL";

export const TOURNAMENT_CREATE_REQUEST = "TOURNAMENT_CREATE_REQUEST";
export const TOURNAMENT_CREATE_SUCCESS = "TOURNAMENT_CREATE_SUCCESS";
export const TOURNAMENT_CREATE_FAIL = "TOURNAMENT_CREATE_FAIL";
export const TOURNAMENT_CREATE_RESET = "TOURNAMENT_CREATE_RESET";

export const TOURNAMENT_UPDATE_REQUEST = "TOURNAMENT_UPDATE_REQUEST";
export const TOURNAMENT_UPDATE_SUCCESS = "TOURNAMENT_UPDATE_SUCCESS";
export const TOURNAMENT_UPDATE_FAIL = "TOURNAMENT_UPDATE_FAIL";
export const TOURNAMENT_UPDATE_RESET = "TOURNAMENT_UPDATE_RESET";
