const usersData = [
  {
    id: 0,
    username: "John Doe",
    registered: "2018/01/01",
    role: "Guest",
    status: "Pending",
  },
  {
    id: 1,
    username: "Samppa Nori",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 2,
    username: "Estavan Lykos",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banned",
  },
  {
    id: 3,
    username: "Chetan Mohamed",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inactive",
  },
  {
    id: 4,
    username: "Derick Maximinus",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
  },
  {
    id: 5,
    username: "Friderik Dávid",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 6,
    username: "Yiorgos Avraamu",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 7,
    username: "Avram Tarasios",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banned",
  },
  {
    id: 8,
    username: "Quintin Ed",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inactive",
  },
  {
    id: 9,
    username: "Enéas Kwadwo",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
  },
  {
    id: 10,
    username: "Agapetus Tadeáš",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 11,
    username: "Carwyn Fachtna",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 12,
    username: "Nehemiah Tatius",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banned",
  },
  {
    id: 13,
    username: "Ebbe Gemariah",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inactive",
  },
  {
    id: 14,
    username: "Eustorgios Amulius",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
  },
  {
    id: 15,
    username: "Leopold Gáspár",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 16,
    username: "Pompeius René",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 17,
    username: "Paĉjo Jadon",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banned",
  },
  {
    id: 18,
    username: "Micheal Mercurius",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inactive",
  },
  {
    id: 19,
    username: "Ganesha Dubhghall",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
  },
  {
    id: 20,
    username: "Hiroto Šimun",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 21,
    username: "Vishnu Serghei",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 22,
    username: "Zbyněk Phoibos",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banned",
  },
  {
    id: 23,
    username: "Aulus Agmundr",
    registered: "2018/01/01",
    role: "Member",
    status: "Pending",
  },
  {
    id: 42,
    username: "Ford Prefect",
    registered: "2001/05/25",
    role: "Alien",
    status: "Don't panic!",
  },
];

export default usersData;
