import Head from 'next/head'
import styles from '../styles/Home.module.css'

const index = () => {
  return (
    <div>
      <Head>
        <title>GamingU2Play</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Welcome to GamingU2Play</h1>
    </div>
  )
}

export default index
